version: 2.1

jobs:
  build-and-test:
    macos:
      xcode: "16.2"
    steps:
      - checkout
      - run:
          name: Select Xcode Version
          command: sudo xcode-select -s /Applications/Xcode_16.1.0.app/Contents/Developer
      - run:
          name: Build
          command: |
            xcodebuild clean build \
              -project Authenticator.xcodeproj \
              -scheme Authenticator \
              -destination 'platform=iOS Simulator,name=iPhone 16 Pro Max,OS=latest' \
              -configuration Debug \
              CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
      - run:
          name: Run UI Smoke Tests
          command: |
            xcodebuild test \
              -project Authenticator.xcodeproj \
              -scheme Authenticator \
              -destination 'platform=iOS Simulator,name=iPhone 16 Pro Max,OS=latest' \
              -configuration Debug \
              -enableCodeCoverage YES \
              -testPlan "UI-Smoke-Tests"
      - run:
          name: Run Unit Smoke Tests
          command: |
            xcodebuild test \
              -project Authenticator.xcodeproj \
              -scheme Authenticator \
              -destination 'platform=iOS Simulator,name=iPhone 16 Pro Max,OS=latest' \
              -configuration Debug \
              -enableCodeCoverage YES \
              -testPlan "Unit-Smoke-Tests"
      - run:
          name: Run Performance Smoke Tests
          command: |
            xcodebuild test \
              -project Authenticator.xcodeproj \
              -scheme Authenticator \
              -destination 'platform=iOS Simulator,name=iPhone 16 Pro Max,OS=latest' \
              -configuration Debug \
              -enableCodeCoverage YES \
              -testPlan "Performance-Smoke-Tests"
      - run:
          name: Generate Code Coverage Report
          command: |
            xccov generate --archive build/Logs/Test/*.xcresult --output codecov.json
      - run:
          name: Upload Code Coverage Reports
          command: |
            curl -Os https://uploader.codecov.io/latest/macos/codecov
            chmod +x codecov
            ./codecov -f codecov.json

workflows:
  build-and-test-workflow:
    jobs:
      - build-and-test
