# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

# Define a job for building and testing an iOS app using macOS executor.
jobs:
  build-and-test-ios:
    macos:
      # Specify the Xcode version needed for your project
      xcode: "14.0.0"
      
    # Steps to execute in the job
    steps:
      - checkout
      
      - run:
          # Use Swift Package Manager (SPM) to resolve dependencies
          name: "Resolve Dependencies using SPM"
          command: |
            xcodebuild -resolvePackageDependencies

      - run:
          # Build the iOS app using xcodebuild
          name: "Build iOS App"
          command: |
            xcodebuild \
              -workspace YourApp.xcworkspace \ # Replace with your workspace
              -scheme YourAppScheme \          # Replace with your app scheme
              -sdk iphonesimulator \
              -configuration Debug \
              clean build
      
      - run:
          # Run unit tests for the iOS app
          name: "Run Unit Tests"
          command: |
            xcodebuild \
              -workspace YourApp.xcworkspace \ # Replace with your workspace
              -scheme YourAppScheme \          # Replace with your app scheme
              -sdk iphonesimulator \
              -configuration Debug \
              -destination 'platform=iOS Simulator,name=iPhone 14' \ # Specify simulator
              clean test

# Define a workflow to orchestrate the job
workflows:
  build-and-test:
    jobs:
      - build-and-test-ios
