name: Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  PROJECT_NAME: Authenticator.xcodeproj
  SCHEME_NAME: Authenticator
  DESTINATION: 'platform=iOS Simulator,name=iPhone 16 Pro Max,OS=latest'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Select Xcode Version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.1.0'

      - name: Cache SPM Packages
        id: cache-spm
        uses: actions/cache@v3
        with:
          path: |
            ~/Library/Caches/org.swift.swiftpm
            ${{ github.workspace }}/.build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Build
        run: |
          xcodebuild clean build \
            -project "${{ env.PROJECT_NAME }}" \
            -scheme "${{ env.SCHEME_NAME }}" \
            -destination "${{ env.DESTINATION }}" \
            -configuration Debug \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO

  test:
    needs: build
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        test-plan: [
          { name: 'UI-Smoke-Tests', output: 'UITests' },
          { name: 'Unit-Smoke-Tests', output: 'UnitTests' },
          { name: 'Performance-Smoke-Tests', output: 'PerfTests' }
        ]
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Select Xcode Version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.1.0'

      - name: Cache SPM Packages
        id: cache-spm
        uses: actions/cache@v3
        with:
          path: |
            ~/Library/Caches/org.swift.swiftpm
            ${{ github.workspace }}/.build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Run ${{ matrix.test-plan.name }}
        run: |
          xcodebuild test \
            -project "${{ env.PROJECT_NAME }}" \
            -scheme "${{ env.SCHEME_NAME }}" \
            -destination "${{ env.DESTINATION }}" \
            -configuration Debug \
            -enableCodeCoverage YES \
            -testPlan "${{ matrix.test-plan.name }}" \
            -resultBundlePath ${{ matrix.test-plan.output }}.xcresult

      - name: Generate Coverage Report
        run: |
          xcrun xccov view --report --json ${{ matrix.test-plan.output }}.xcresult > ${{ matrix.test-plan.output }}-coverage.json

      - name: Store Test Results and Coverage
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ matrix.test-plan.output }}-results
          path: |
            ${{ matrix.test-plan.output }}.xcresult
            ${{ matrix.test-plan.output }}-coverage.json

      # --- Optional: Fastlane Integration (for more advanced build/release automation) ---
      # - name: Run Fastlane
      #   run: bundle exec fastlane your_lane_name
      #   env:
      #     FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
      #     MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}

      # --- Optional: Upload Artifacts ---
      # - name: Upload IPA
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: Authenticator.ipa
      #     path: path/to/your/ipa/file.ipa

     
