name: iOS CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]
  workflow_dispatch:

env:
  PROJECT_NAME: Authenticator.xcodeproj  # Project name
  SCHEME_NAME: Authenticator          # Scheme name (likely the same)
  DESTINATION: 'platform=iOS Simulator,name=iPhone 14,OS=latest'

jobs:
  build-and-test:
    name: Build and Test
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Select Xcode Version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.1.0'  # Adjust as needed

      # --- Swift Package Manager Cache (Optional, but recommended for speed) ---
      - name: Cache SPM Packages
        id: cache-spm
        uses: actions/cache@v3
        with:
          path: |
            ~/Library/Caches/org.swift.swiftpm
            ${{ github.workspace }}/.build  # Cache the .build directory as well
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Build
        run: |
          xcodebuild clean build -project "${{ env.PROJECT_NAME }}" -scheme "${{ env.SCHEME_NAME }}" -destination "${{ env.DESTINATION }}" -configuration Debug CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

      - name: Run Tests
        run: |
          xcodebuild test -project "${{ env.PROJECT_NAME }}" -scheme "${{ env.SCHEME_NAME }}" -destination "${{ env.DESTINATION }}" -configuration Debug -enableCodeCoverage YES -only-testing:AuthenticatorTests # Assuming your test target is named AuthenticatorTests

      - name: Upload Code Coverage Reports (Optional)
        uses: codecov/codecov-action@v3
        with:
             files: ${{ github.workspace }}/your_report.xml # Path to the XML report. Adjust as needed.
             fail_ci_if_error: true


      # --- Optional: Fastlane Integration (for more advanced build/release automation) ---
      # - name: Run Fastlane
      #   run: bundle exec fastlane your_lane_name
      #   env:
      #     FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
      #     MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}

      # --- Optional: Upload Artifacts ---
      # - name: Upload IPA
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: Authenticator.ipa
      #     path: path/to/your/ipa/file.ipa

      # --- Optional: Notify on Failure ---
      # - name: Send Slack Notification on Failure
      #   if: failure()
      #   uses: slackapi/slack-github-action@v1.23.0
      #   with:
      #     channel-id: 'your-channel-id'
      #     payload: |
      #       {
      #         "text": "❌ Build failed for Authenticator on branch ${{ github.ref }}",
      #         "attachments": [
      #           {
      #             "color": "#ff0000",
      #             "fields": [
      #               {
      #                 "title": "Commit",
      #                 "value": "${{ github.sha }}",
      #                 "short": true
      #               },
      #               {
      #                 "title": "Workflow Run",
      #                 "value": "<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Run>",
      #                 "short": true
      #               }
      #             ]
      #           }
      #         ]
      #       }
      #   env:
      #     SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
